# Generated by Django 5.2.13 on 2026-07-19 17:50

import django.db.models.deletion
from django.db import migrations, models


def migrate_order_items_and_carts(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")
    ProductVariant = apps.get_model("products", "ProductVariant")

    # Preserve commercial data first. A variant is assigned only when the
    # catalogue match is unambiguous; historical ambiguous rows remain nullable.
    for item in OrderItem.objects.select_related("product").iterator():
        if item.product_id:
            item.product_name = item.product.name
            item.unit_price = item.product.price
            variants = list(
                ProductVariant.objects.filter(product_id=item.product_id)[:2]
            )
            if len(variants) == 1:
                variant = variants[0]
                item.variant_id = variant.id
                item.color_name = variant.color.name if variant.color_id else ""
                item.size_name = variant.size.name if variant.size_id else ""
                item.sku = variant.sku
                if variant.price is not None:
                    item.unit_price = variant.price
            item.save(update_fields=[
                "product_name", "unit_price", "variant", "color_name",
                "size_name", "sku",
            ])

    # The unambiguous backfill can make legacy duplicate product rows point to
    # the same variant. Merge those rows before the unique index is installed.
    for order_id, variant_id in (
        OrderItem.objects.filter(variant_id__isnull=False)
        .values_list("order_id", "variant_id").distinct()
    ):
        rows = list(
            OrderItem.objects.filter(order_id=order_id, variant_id=variant_id)
            .order_by("id")
        )
        if len(rows) > 1:
            primary_item = rows[0]
            primary_item.quantity = sum(row.quantity for row in rows)
            primary_item.save(update_fields=["quantity"])
            OrderItem.objects.filter(pk__in=[row.pk for row in rows[1:]]).delete()

    # Consolidate legacy duplicate active carts before installing the partial
    # unique constraint. Paid/completed orders are never touched.
    customer_ids = (
        Order.objects.filter(complete=False, customer_id__isnull=False)
        .values_list("customer_id", flat=True).distinct()
    )
    for customer_id in customer_ids:
        carts = list(
            Order.objects.filter(customer_id=customer_id, complete=False)
            .order_by("date_ordered", "id")
        )
        if len(carts) < 2:
            continue
        primary = next((cart for cart in carts if cart.items.exists()), carts[0])
        for duplicate in carts:
            if duplicate.id == primary.id:
                continue
            for item in list(duplicate.items.all()):
                existing = None
                if item.variant_id:
                    existing = primary.items.filter(variant_id=item.variant_id).first()
                if existing:
                    existing.quantity += item.quantity
                    existing.save(update_fields=["quantity"])
                    item.delete()
                else:
                    item.order_id = primary.id
                    item.save(update_fields=["order"])
            duplicate.delete()


class Migration(migrations.Migration):
    # PostgreSQL cannot create the partial unique indexes in the same
    # transaction as the legacy-cart consolidation deletes.
    atomic = False

    dependencies = [
        ('orders', '0004_alter_order_status'),
        ('products', '0006_alter_productvariant_unique_together_and_more'),
        ('users', '0002_remove_customer_phone_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant'),
        ),
        migrations.RunPython(migrate_order_items_and_carts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('complete', False)), fields=('customer',), name='unique_active_cart_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_valid'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('order', 'variant'), name='unique_variant_per_cart'),
        ),
    ]
