# Generated by Django 5.2.13 on 2026-07-19 18:07

from decimal import Decimal
from django.db import migrations, models


def backfill_order_snapshots(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")
    Payment = apps.get_model("payments", "Payment")

    for item in OrderItem.objects.all().iterator():
        item.product_reference = item.product_id
        item.variant_reference = item.variant_id
        item.variant_name = " / ".join(
            value for value in (item.color_name, item.size_name) if value
        )
        if item.unit_price is not None:
            item.currency = "XOF"
            item.subtotal = (
                item.unit_price * item.quantity - item.discount_amount
            ).quantize(Decimal("0.01"))
        item.save(update_fields=[
            "product_reference", "variant_reference", "variant_name",
            "currency", "subtotal",
        ])

    for order in Order.objects.select_related("customer__user").all().iterator():
        if order.customer_id:
            user = order.customer.user
            order.customer_name = (
                f"{user.first_name} {user.last_name}".strip() or user.username
            )
            order.customer_email = user.email
            order.delivery_recipient_name = order.customer_name
            order.delivery_phone = order.customer.phone_number
            order.delivery_address = order.customer.address
            order.delivery_country = order.customer.country

        line_subtotals = list(
            OrderItem.objects.filter(order_id=order.id)
            .values_list("subtotal", flat=True)
        )
        if line_subtotals and all(value is not None for value in line_subtotals):
            order.subtotal_amount = sum(line_subtotals, Decimal("0.00"))

        confirmed = (
            Payment.objects.filter(order_id=order.id, status="completed")
            .order_by("-processed_at", "-id")
            .first()
        )
        if confirmed:
            order.total_amount = confirmed.amount
            order.currency = confirmed.currency
        elif order.subtotal_amount is not None:
            order.total_amount = order.subtotal_amount

        if order.complete:
            order.snapshot_at = order.paid_at or order.date_ordered
        order.save(update_fields=[
            "customer_name", "customer_email", "delivery_recipient_name",
            "delivery_phone", "delivery_address", "delivery_country",
            "subtotal_amount", "total_amount", "currency", "snapshot_at",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_color_name_orderitem_product_name_and_more'),
        ('payments', '0008_add_mock_provider'),
        ('products', '0006_alter_productvariant_unique_together_and_more'),
        ('users', '0002_remove_customer_phone_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_country',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_recipient_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_reference',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_reference',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_order_snapshots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__isnull', True), ('subtotal_amount__gte', 0), _connector='OR'), name='order_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_amount__gte', 0)), name='order_shipping_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='order_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__isnull', True), ('total_amount__gte', 0), _connector='OR'), name='order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__isnull', True), ('unit_price__gte', 0), _connector='OR'), name='order_item_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='order_item_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__isnull', True), ('subtotal__gte', 0), _connector='OR'), name='order_item_subtotal_non_negative'),
        ),
    ]
