# Generated by Django 5.2.13 on 2026-07-19 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_statuses(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.all().iterator():
        legacy = order.status
        if legacy == "pending":
            order.status = "pending_payment" if order.snapshot_at else "cart"
        elif legacy == "failed":
            order.status = "cancelled"
            order.cancelled_at = order.date_ordered
        elif legacy not in {"paid", "cancelled", "refunded"}:
            order.status = "cart" if not order.snapshot_at else "pending_payment"
        if order.status in {"paid", "refunded"}:
            order.stock_consumed_at = order.paid_at or order.date_ordered
        if order.status == "refunded":
            order.refunded_at = order.paid_at or order.date_ordered
        order.save(update_fields=[
            "status", "cancelled_at", "stock_consumed_at", "refunded_at",
        ])


def backfill_initial_history(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    History = apps.get_model("orders", "OrderStatusHistory")
    for order in Order.objects.all().iterator():
        history = History.objects.create(
            order_id=order.id,
            from_status="",
            to_status=order.status,
            actor_role_snapshot="migration",
            reason_code="legacy_backfill",
            metadata={"legacy": True},
        )
        reliable_date = order.paid_at or order.date_ordered
        History.objects.filter(pk=history.pk).update(created_at=reliable_date)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_currency_order_customer_email_and_more'),
        ('users', '0002_remove_customer_phone_customer_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('cart', 'Cart'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded'), ('refund_failed', 'Refund failed')], max_length=20)),
                ('actor_role_snapshot', models.CharField(blank=True, max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('reason_note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_active_cart_per_customer',
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded'), ('refund_failed', 'Refund failed')], default='cart', max_length=20),
        ),
        migrations.RunPython(migrate_legacy_statuses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cart')), fields=('customer',), name='unique_active_cart_per_customer'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='orders.order'),
        ),
        migrations.RunPython(backfill_initial_history, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='orderstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='order_history_status_changed'),
        ),
    ]
