# Generated by Django 5.2.13 on 2026-07-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_checkout_snapshots_and_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('pending_payment', 'Pending payment'), ('payment_processing', 'Payment processing'), ('payment_failed', 'Payment failed'), ('paid', 'Paid'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refund_required', 'Refund required'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded'), ('refund_failed', 'Refund failed')], default='cart', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('cart', 'Cart'), ('pending_payment', 'Pending payment'), ('payment_processing', 'Payment processing'), ('payment_failed', 'Payment failed'), ('paid', 'Paid'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refund_required', 'Refund required'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded'), ('refund_failed', 'Refund failed')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrderNotificationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=50)),
                ('channel', models.CharField(default='email', max_length=20)),
                ('recipient_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_receipts', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='order_notif_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'event_code', 'channel'), name='unique_order_notification_event_channel')],
            },
        ),
    ]
