# Generated by Django 5.2.13 on 2026-07-20 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_expired_at_order_payment_failed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=32, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('document_type', models.CharField(default='order_receipt', editable=False, max_length=32)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
