# Generated by Django 5.2.13 on 2026-07-23 12:29

import django.db.models.functions.math
import store.money
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_stock_reservation'),
        ('products', '0010_alter_product_price_alter_productvariant_price_and_more'),
        ('users', '0004_account_security_data_and_email_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[store.money.validate_xof_integer]),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[store.money.validate_xof_integer]),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[store.money.validate_xof_integer]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[store.money.validate_xof_integer]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[store.money.validate_xof_integer]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[store.money.validate_xof_integer]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[store.money.validate_xof_integer]),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__isnull', True), ('subtotal_amount', django.db.models.functions.math.Floor('subtotal_amount')), _connector='OR'), name='order_subtotal_xof_integer'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_amount', django.db.models.functions.math.Floor('shipping_amount'))), name='order_shipping_xof_integer'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount', django.db.models.functions.math.Floor('discount_amount'))), name='order_discount_xof_integer'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__isnull', True), ('total_amount', django.db.models.functions.math.Floor('total_amount')), _connector='OR'), name='order_total_xof_integer'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__isnull', True), ('unit_price', django.db.models.functions.math.Floor('unit_price')), _connector='OR'), name='order_item_price_xof_integer'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount', django.db.models.functions.math.Floor('discount_amount'))), name='order_item_discount_xof_integer'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__isnull', True), ('subtotal', django.db.models.functions.math.Floor('subtotal')), _connector='OR'), name='order_item_subtotal_xof_integer'),
        ),
    ]
