# Generated by Django 5.2.13 on 2026-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, help_text='Code pays ISO (ex: FR, ML)', max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone au format international', max_length=20),
        ),
    ]
