"""
Django settings for lobel_store project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
from datetime import timedelta

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env(
    DEBUG=(bool, True),
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOW_ALL_ORIGINS=(bool, True),
    DATABASE_PORT=(int, 5433),
    API_DEFAULT_PAGE_SIZE=(int, 20),
    API_MAX_PAGE_SIZE=(int, 100),
    API_MAX_SEARCH_LENGTH=(int, 100),
)
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ""

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Django forces DEBUG=False while running tests. This internal flag allows
# explicitly selected test providers without creating a production override.
TESTING = False

ALLOWED_HOSTS = []

# En dev local (PC + téléphone sur le même réseau), autoriser toutes les origines Host
# si ALLOWED_HOSTS n'est pas défini dans .env


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'users',
    'products',
    'orders',
    'payments',
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lobel_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lobel_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom authentication backend for email login
AUTHENTICATION_BACKENDS = [
    'users.custom_auth.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.AccountJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'register': '10/hour',
        'login': '10/minute',
        'token_refresh': '30/hour',
        'logout': '30/hour',
        'password_reset_request': '5/hour',
        'password_reset_request_email': '5/hour',
        'password_reset_confirm': '10/hour',
        'email_activation': '10/hour',
        'password_change': '10/hour',
        'catalog_media_upload': '30/hour',
        'payment_initialize': '10/minute',
        'payment_refresh': '30/minute',
        'payment_callback': '120/minute',
    },
    'NUM_PROXIES': env.int('DRF_NUM_PROXIES', default=0),
    'DEFAULT_PAGINATION_CLASS': 'lobel_store.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': env('API_DEFAULT_PAGE_SIZE'),
}

SWAGGER_SETTINGS = {
    'DEFAULT_INFO': 'lobel_store.urls.api_info',
}

API_DEFAULT_PAGE_SIZE = env('API_DEFAULT_PAGE_SIZE')
API_MAX_PAGE_SIZE = env('API_MAX_PAGE_SIZE')
API_MAX_SEARCH_LENGTH = env('API_MAX_SEARCH_LENGTH')
if API_DEFAULT_PAGE_SIZE <= 0 or API_MAX_PAGE_SIZE < API_DEFAULT_PAGE_SIZE:
    raise ValueError("API page sizes must be positive and maximum >= default.")
if API_MAX_SEARCH_LENGTH <= 0:
    raise ValueError("API_MAX_SEARCH_LENGTH must be positive.")

JWT_ACCESS_MINUTES = env.int('JWT_ACCESS_MINUTES', default=15)
JWT_REFRESH_DAYS = env.int('JWT_REFRESH_DAYS', default=7)
if JWT_ACCESS_MINUTES <= 0 or JWT_REFRESH_DAYS <= 0:
    raise ValueError("JWT_ACCESS_MINUTES and JWT_REFRESH_DAYS must be positive integers.")

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=JWT_ACCESS_MINUTES),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=JWT_REFRESH_DAYS),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

EMAIL_BACKEND = ""
DEFAULT_FROM_EMAIL = ""
FRONTEND_URL = ""
FRONTEND_RESET_PASSWORD_URL = ""
FRONTEND_EMAIL_ACTIVATION_URL = ""

# Explicit selection is mandatory. The mock provider is development/test only
# and is rejected whenever DEBUG=False.
PAYMENT_PROVIDER = ""
LIGDICASH_API_KEY = ""
LIGDICASH_API_TOKEN = ""
LIGDICASH_BASE_URL = ""
LIGDICASH_STORE_NAME = ""
LIGDICASH_STORE_URL = ""
LIGDICASH_RETURN_URL = ""
LIGDICASH_CANCEL_URL = ""
LIGDICASH_CALLBACK_URL = ""
LIGDICASH_ENVIRONMENT = ""
LIGDICASH_HTTP_TIMEOUT = 15
LIGDICASH_VERIFY_TLS = True
LIGDICASH_ALLOWED_CHECKOUT_HOSTS = ["app.ligdicash.com"]
ORDER_PENDING_PAYMENT_TTL_MINUTES = env.int(
    "ORDER_PENDING_PAYMENT_TTL_MINUTES", default=60
)
if ORDER_PENDING_PAYMENT_TTL_MINUTES <= 0:
    raise ValueError("ORDER_PENDING_PAYMENT_TTL_MINUTES must be positive.")

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_STORAGE_BACKEND = 'local'
MAX_IMAGE_UPLOAD_MB = env.int('MAX_IMAGE_UPLOAD_MB', default=5)
MAX_VIDEO_UPLOAD_MB = env.int('MAX_VIDEO_UPLOAD_MB', default=50)
MAX_PRODUCT_IMAGES = env.int('MAX_PRODUCT_IMAGES', default=10)
MAX_PRODUCT_VIDEOS = env.int('MAX_PRODUCT_VIDEOS', default=2)
MAX_IMAGE_WIDTH = env.int('MAX_IMAGE_WIDTH', default=8000)
MAX_IMAGE_HEIGHT = env.int('MAX_IMAGE_HEIGHT', default=8000)
MAX_IMAGE_PIXELS = env.int('MAX_IMAGE_PIXELS', default=40_000_000)
MAX_VIDEO_DURATION_SECONDS = env.int('MAX_VIDEO_DURATION_SECONDS', default=120)
MAX_VIDEO_WIDTH = env.int('MAX_VIDEO_WIDTH', default=1920)
MAX_VIDEO_HEIGHT = env.int('MAX_VIDEO_HEIGHT', default=1080)
MAX_VIDEO_TRACKS = env.int('MAX_VIDEO_TRACKS', default=4)
FFPROBE_PATH = env('FFPROBE_PATH', default='')
FFPROBE_TIMEOUT_SECONDS = env.int('FFPROBE_TIMEOUT_SECONDS', default=10)
for setting_name in (
    'MAX_IMAGE_UPLOAD_MB', 'MAX_VIDEO_UPLOAD_MB', 'MAX_PRODUCT_IMAGES',
    'MAX_PRODUCT_VIDEOS', 'MAX_IMAGE_WIDTH', 'MAX_IMAGE_HEIGHT',
    'MAX_IMAGE_PIXELS', 'MAX_VIDEO_DURATION_SECONDS', 'MAX_VIDEO_WIDTH',
    'MAX_VIDEO_HEIGHT', 'MAX_VIDEO_TRACKS', 'FFPROBE_TIMEOUT_SECONDS',
):
    if globals()[setting_name] <= 0:
        raise ValueError(f"{setting_name} must be a positive integer.")
MAX_IMAGE_UPLOAD_BYTES = MAX_IMAGE_UPLOAD_MB * 1024 * 1024
MAX_VIDEO_UPLOAD_BYTES = MAX_VIDEO_UPLOAD_MB * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = (MAX_VIDEO_UPLOAD_MB + 1) * 1024 * 1024

# --- CORS & réseau local (développement) ---
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = []
CSRF_TRUSTED_ORIGINS = []
ENABLE_API_DOCS = False
