# Generated by Django 5.2.13 on 2026-04-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='collections/videos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/images/'),
        ),
    ]
