# Generated by Django 5.2.13 on 2026-07-19 21:11

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_is_active_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='collection',
            name='duration_seconds',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='format',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='collection',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='mime_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='collection',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='duration_seconds',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='format',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='mime_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.collection_image_upload_to),
        ),
        migrations.AlterField(
            model_name='collection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=products.models.collection_video_upload_to),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(upload_to=products.models.product_media_upload_to),
        ),
    ]
