# Generated by Django 5.2.13 on 2026-07-23 12:29

import django.db.models.functions.math
import store.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_protect_variant_color_and_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[store.money.validate_xof_integer]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[store.money.validate_xof_integer]),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price', django.db.models.functions.math.Floor('price'))), name='product_price_xof_integer'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price', django.db.models.functions.math.Floor('price')), _connector='OR'), name='variant_price_xof_integer'),
        ),
    ]
