# Generated by Django 5.2.13 on 2026-06-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('senepay', 'SenePay')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
