# Generated by Django 5.2.13 on 2026-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_currency_payment_external_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('senepay', 'SenePay')], max_length=20),
        ),
    ]
