# Generated by Django 5.2.13 on 2026-06-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
