# Generated by Django 5.2.13 on 2026-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
