# Generated by Django 5.2.13 on 2026-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_replace_senepay_with_ligdicash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('mock', 'Mock'), ('ligdicash', 'LigdiCash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('mock', 'Mock'), ('ligdicash', 'LigdiCash')], default='manual', max_length=30),
        ),
    ]
