# Generated by Django 5.2.13 on 2026-07-23 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_stock_reservation'),
        ('payments', '0011_payment_duplicate_protection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='requested', max_length=20)),
                ('affects_order_status', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=500)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('provider_status', models.CharField(blank=True, max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RefundAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('reconcile', 'Reconcile')], max_length=20)),
                ('result', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='started', max_length=20)),
                ('provider_status', models.CharField(blank=True, max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('response_code', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='payments.refund')),
            ],
            options={
                'ordering': ['refund_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='RefundNotificationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=50)),
                ('recipient_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_receipts', to='payments.refund')),
            ],
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'requested_at'], name='refund_reconcile_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('payment', 'idempotency_key'), name='unique_refund_key_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='refundattempt',
            constraint=models.UniqueConstraint(fields=('refund', 'sequence'), name='unique_refund_attempt_sequence'),
        ),
        migrations.AddConstraint(
            model_name='refundnotificationreceipt',
            constraint=models.UniqueConstraint(fields=('refund', 'event_code'), name='unique_refund_notification_event'),
        ),
    ]
