# Generated by Django 5.2.13 on 2026-07-23 12:29

import django.db.models.functions.math
import store.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_discount_amount_and_more'),
        ('payments', '0012_refund_refundattempt_refundnotificationreceipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[store.money.validate_xof_integer]),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[store.money.validate_xof_integer]),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.functions.math.Floor('amount'))), name='payment_amount_xof_integer'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.functions.math.Floor('amount'))), name='refund_amount_xof_integer'),
        ),
    ]
