# Generated by Django 5.2.13 on 2026-07-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_payment_amount_alter_refund_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='authentication_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='provider_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='signature_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='source_ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
