# Generated by Django 5.2.13 on 2026-07-20 12:57

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(max_length=600)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo')], default='IMAGE', max_length=10)),
                ('desktop_image', models.ImageField(blank=True, help_text='Recommandé : 1920 × 1080 px, JPEG/PNG/WebP.', null=True, upload_to=content.models.hero_upload_to)),
                ('mobile_image', models.ImageField(blank=True, help_text='Facultatif. Recommandé : 1080 × 1350 px.', null=True, upload_to=content.models.hero_upload_to)),
                ('video', models.FileField(blank=True, help_text='MP4 H.264 court et compressé, sans piste audio nécessaire.', null=True, upload_to=content.models.hero_upload_to)),
                ('video_poster', models.ImageField(blank=True, help_text="Image affichée avant chargement, en cas d'erreur ou de mouvement réduit.", null=True, upload_to=content.models.hero_upload_to)),
                ('primary_button_label', models.CharField(default='Voir la boutique', max_length=80)),
                ('primary_button_url', models.CharField(default='/shop', max_length=500, validators=[content.models.validate_button_url])),
                ('secondary_button_label', models.CharField(blank=True, max_length=80)),
                ('secondary_button_url', models.CharField(blank=True, max_length=500, validators=[content.models.validate_button_url])),
                ('is_active', models.BooleanField(default=False, help_text="L'activation désactive automatiquement toute autre couverture.")),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_home_hero')],
            },
        ),
    ]
