# Generated by Django for the targeted custom dress service.

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDressService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "description",
                    models.TextField(
                        max_length=1000,
                        validators=[content.models.validate_plain_text],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="JPEG, PNG ou WebP.",
                        upload_to=content.models.custom_dress_upload_to,
                    ),
                ),
                (
                    "whatsapp_phone",
                    models.CharField(
                        help_text=(
                            "8 à 15 chiffres au format international, "
                            "sans +, espace ni tiret."
                        ),
                        max_length=15,
                        validators=[content.models.validate_whatsapp_phone],
                    ),
                ),
                (
                    "whatsapp_message",
                    models.TextField(
                        help_text=(
                            "Message générique uniquement : aucune donnée personnelle."
                        ),
                        max_length=1000,
                        validators=[content.models.validate_plain_text],
                    ),
                ),
                (
                    "button_label",
                    models.CharField(
                        default="Discuter sur WhatsApp", max_length=80
                    ),
                ),
                (
                    "availability_text",
                    models.CharField(blank=True, max_length=240),
                ),
                (
                    "response_time_text",
                    models.CharField(blank=True, max_length=240),
                ),
                (
                    "pricing_notice",
                    models.CharField(
                        max_length=400,
                        validators=[content.models.validate_plain_text],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "L'activation désactive automatiquement "
                            "l'ancienne configuration."
                        ),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="unique_active_custom_dress_service",
                    )
                ],
            },
        ),
    ]
